# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

    # Organization controlling both peers and Orderers
    - &AidTech
        Name: AidTech

        # ID to load the MSP definition as
        ID: AidTechMSP

        MSPDir: ./AidTechMSP

        # turn off security for the peer
        AdminPrincipal: Role.MEMBER

        AnchorPeers:
            # AnchorPeers defines the location of peers that can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer1-hlf-peer.blockchain.svc.cluster.local
              Port: 7051
            - Host: peer2-hlf-peer.blockchain.svc.cluster.local
              Port: 7051

################################################################################
#
#   SECTION: Orderer
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for orderer related parameters
#
################################################################################
Orderer: &OrdererDefaults

    # Orderer Type: The orderer implementation to start
    # Available types are "solo","kafka"  and "etcdraft"
    OrdererType: etcdraft

    Addresses:
        - ord1-hlf-ord.blockchain.svc.cluster.local:7050
        - ord2-hlf-ord.blockchain.svc.cluster.local:7050
        - ord3-hlf-ord.blockchain.svc.cluster.local:7050

    # Batch Timeout: The amount of time to wait before creating a batch
    BatchTimeout: 2s

    # Batch Size: Controls the number of messages batched into a block
    BatchSize:

        # Max Message Count: The maximum number of messages to permit in a batch
        MaxMessageCount: 10

        # Absolute Max Bytes: The absolute maximum number of bytes allowed for
        # the serialized messages in a batch.
        AbsoluteMaxBytes: 98 MB

        # Preferred Max Bytes: The preferred maximum number of bytes allowed for
        # the serialized messages in a batch. A message larger than the preferred
        # max bytes will result in a batch larger than preferred max bytes.
        PreferredMaxBytes: 512 KB

    Kafka:
        # Brokers: A list of Kafka brokers to which the orderer connects
        # If using K8S, we specify the service exposing the brokers
        # NOTE: Use Address/IP:port notation
        Brokers:
            - kafka-hlf.blockchain.svc.cluster.local:9092

    # https://github.com/hyperledger/fabric-samples/blob/release-1.4/first-network/configtx.yaml
    # EtcdRaft defines configuration which must be set when the "etcdraft"
    # orderertype is chosen.
    EtcdRaft:
        # The set of Raft replicas for this network. For the etcd/raft-based
        # implementation, we expect every replica to also be an OSN. Therefore,
        # a subset of the host:port items enumerated in this list should be
        # replicated under the Orderer.Addresses key above.
        Consenters:
            - Host: ord1-hlf-ord.blockchain.svc.cluster.local:7050
              Port: 7050
              ClientTLSCert: /var/hyperledger/msp/signcerts/cert.pem
              ServerTLSCert: /var/hyperledger/msp/signcerts/cert.pem
            - Host: ord2-hlf-ord.blockchain.svc.cluster.local:7050
              Port: 7050
              ClientTLSCert: /var/hyperledger/msp/signcerts/cert.pem
              ServerTLSCert: /var/hyperledger/msp/signcerts/cert.pem
            - Host: ord3-hlf-ord.blockchain.svc.cluster.local:7050
              Port: 7050
              ClientTLSCert: /var/hyperledger/msp/signcerts/cert.pem
              ServerTLSCert: /var/hyperledger/msp/signcerts/cert.pem


    # Organizations is the list of orgs which are defined as participants on
    # the orderer side of the network
    Organizations:

################################################################################
#
#   SECTION: Application
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults

    # Organizations is the list of orgs which are defined as participants on
    # the application side of the network
    Organizations:

################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:

    OrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *AidTech
        Consortiums:
            MyConsortium:
                Organizations:
                    - *AidTech
    MyChannel:
        Consortium: MyConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *AidTech
