image:
  tag: 1.4.6
  
persistence:
  accessMode: ReadWriteOnce
  size: 1Gi

peer:
  databaseType: CouchDB
  couchdbInstance: cdb-peer1
  mspID: AidTechMSP

secrets:
  peer:
    cert: hlf--peer1-idcert
    key: hlf--peer1-idkey
    caCert: hlf--ca-cert
  channels:
    - "hlf--channel"
  adminCert: hlf--org-admincert
  adminKey: hlf--org-adminkey
  caServerTls: ca--tls

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 95
        podAffinityTerm:
          topologyKey: "kubernetes.io/hostname"
          labelSelector:
            matchLabels:
              app: hlf-peer
